name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Change folder
      run: cd database-migration
    - name: Install dependencies
      run: dotnet restore
    - name: Run
      env: # Or as an environment variable
        ConnectionString: ${{ secrets.CONNECTIONSTRING }}
      run: dotnet run
    
